### ISSUE TITLE
pip freeze doesn't work

### ISSUE THREAD

**Issue by daikema** [idia-astro/idia-container-sourcefinding#1]
```
$ pip freeze
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 74, in <module>
    __import__('pip._vendor.packaging.requirements')
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/packaging/requirements.py", line 9, in <module>
    from pip._vendor.pyparsing import (
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 762, in get_code
  File "<frozen importlib._bootstrap_external>", line 473, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
```

**Comment by daikema** [comment]
So, while poking around the other issue, I discovered that the cause of this appears to be that /usr/local/bin contains Python 3.5 executables whereas Python 2.7 is what most of our systems packages are.  Still not sure what's installing python 3.5 there - I seem to recall encountering this on another system not in a singularity container yesterday as well.

So, for the moment `pip freeze` won't work but `/usr/bin/pip freeze` will (and `/usr/local/bin/pip2 freeze` also will work).  Timestamp on `/usr/local/bin/pip` is July 31 - I'm not sure what changes were made to the container around then.

@Shadowphax were you already working on the sourcefinding rebuild right (which should also address #2 I imagine)?

**Comment by Shadowphax** [comment]
We have redeployed the container based on a number of improvements within the build definition file. There are currently two source finding containers. The most recent one is " sourcefinding.img" which is a symbolic link to the "sourcefinding-<commit>.img". Please no longer use the "source-finding.img" container.

**Comment by Shadowphax** [comment]
Closing issue
