### ISSUE TITLE
I get an error with pybdsf which I think is from numpy. Can you update numpy?

### ISSUE THREAD

**Issue by EFOcran** [idia-astro/idia-container-sourcefinding#3]

**Comment by Shadowphax** [comment]
Can you provide the error message please ?

**Comment by EFOcran** [comment]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by Shadowphax** [comment]
The source finding container is running the latest version of numpy==1.13.3. The source finding container was rebuilt last week which would have the latest of all the python modules. You are welcome to execute " ./sourcefinding.img" from the terminal to see a list of installed python modules and versions.

**Comment by EFOcran** [comment]
Remember I used to get the error  :
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices.
But when I started using /sourcefinding.img container instead of /source-finding.img it was ok. Now that David has installed pybdsf, the same error comes up again.

**Comment by EFOcran** [comment]
Hello gain, so I now import bdsf instead of from lofar  import bdsm, and this is what I get;

Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
Fitting isl # 54 ; # pix =  50 ; size =  1.13105186976
Process Process-90:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed
Process Process-91:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed
Fitting isl # 110 ; # pix =  76 ; size =  1.71919884203
Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
Process Process-92:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed
Fitting isl # 165 ; # pix =  58 ; size =  1.31202016892
Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
Process Process-93:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed
Fitting isl # 221 ; # pix =  175 ; size =  3.95868154415
Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
Process Process-94:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed
Fitting isl # 280 ; # pix =  47 ; size =  1.06318875757
Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
Process Process-95:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed
Fitting isl # 338 ; # pix =  41 ; size =  0.9274625332
Thread raised exception Python argument types in
    MGFunction.add_gaussian(MGFunction, Gtype, tuple)
did not match C++ signature:
    add_gaussian(MGFunction {lvalue}, MGFunction::Gtype type, boost::python::api::object parameters)
Traceback of thread is:
-------------------------
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 53, in worker
    result = f(val)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2044, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 238, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 305, in fit_island
    fitok = self.fit_iter(gaul, ng1, fcn, dof, beam, thr0, iter, ini_gausfit, ngmax, verbose, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 623, in fit_iter
    self.add_gaussian(fcn, g, dof, g3_only)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 678, in add_gaussian
    fcn.add_gaussian(gtype, parameters)
-------------------------
Process Process-96:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bdsf-1.8.12-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 61, in worker
    err_q.put(e)
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
PicklingError: Can't pickle <class 'Boost.Python.ArgumentError'>: import of module Boost.Python failed

**Comment by EFOcran** [comment]
Can we get numba, http://numba.pydata.org/, installed on dipper. I want to use it to increase the speed  of my code.

**Comment by Shadowphax** [comment]
Numba has been installed. Would be great to have some sort of unit testing done.

**Comment by EFOcran** [comment]
Can we install the following latex packages  on dipper?

dvipng
texlive-latex-extras
 texlive-fonts-recommended

**Comment by EFOcran** [comment]
Also can we install java on dipper?

**Comment by Shadowphax** [comment]
Hi,
Can you please log a separate issue for these installs ? Its just so that we can keep track. 

Java
dvipng
texlive-latex-extras
texlive-fonts-recommended

Thanks

**Comment by Shadowphax** [comment]
Hi. 

I have included Java, dvipng, texlive-latex-extras, texlive-fonts-recommended. The updated container has been deployed. 

Regards

**Comment by EFOcran** [comment]
Hi ,

Can we get ds9 installed on dipper?

**Comment by Shadowphax** [comment]
ds9 has always been in the container. In future, please use " singularity shell sourcefinding.img" and execute the name of the application.
